### ISSUE TITLE
Gruppenmeetings KW 4 (23.-29.1.2023)

### ISSUE THREAD

**Issue by sajosa** [Fuenfgeld/DMA2023TeamD#38]
Google Meet-Teilnahmeinformationen
Link für Videoanruf: https://meet.google.com/mwf-jahn-gxt
Oder telefonisch: ‪(DE) +49 40 8081616676‬ PIN: ‪304 294 033‬#
Weitere Telefonnummern: https://tel.meet/mwf-jahn-gxt?pin=1838082169126

**Comment by sajosa** [comment]
**To Dos von Onlinemeeting (23.01.2023)**: @JanEricSch @GisstHubana 


- [ ] In der WIKI Code Dokumentation mit Link aus der Code Basis
- [ ] Datenmanagementplan!!!
- [x] keine Daten ins repository (schnauf, so haben wir es gemacht)

- [x] Code zu Issues verlinken

- [x] Datenbanken schon auf SQL Ebene kombinieren

- [ ] in WIKI die zu verwendenden Daten dokumentieren https://github.com/Fuenfgeld/DMA2023TeamD/issues/6
- [ ] Abschließende Einigung Forschungsfrage https://github.com/Fuenfgeld/DMA2023TeamD/issues/5

**Comment by sajosa** [comment]
- [ ] Datenbanken schon auf SQL Ebene kombinieren 
- [ ] in WIKI die zu verwendenden Daten dokumentieren #6 
- [ ] Abschliessende EinigungForschungsfrage #5

**Comment by GisstHubana** [comment]
Sofern es sich mit Internet und Urlaub vereinbare lässt, bin ich dafür, dass wir uns morgen nach dem Kurs wieder treffen. Würde euch das passen? @sajosa @JanEricSch

**Comment by sajosa** [comment]
Wäre auch zum Test meiner Verbindung dankbar für einen kurzen call vorher?

**Comment by GisstHubana** [comment]
Ja klar! So 19.15 Uhr? Oder viel früher? Ich könnte wahrscheinlich auch so 18 Uhr schaffen 😊
